# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run 0
    - run: npm run 1
    - run: npm run 2
    - run: npm run 3
    - run: npm run 4
    - run: npm run 5
    - run: npm run 6
    - run: npm run 7
    - run: npm run 8
    - run: npm run 9
    - run: npm run 10
    - run: npm run 11
    - run: npm run 12
    - run: npm run 13
    - run: npm run 14
    - run: npm run 15
